package:
  name: autocnet_server
  version: 0.1.5

source:
   git_url: https://github.com/USGS-Astrogeology/autocnet_server.git
   
requirements:
  build:
    - python
    - autocnet
    - redis
    - sqlalchemy
    - geoalchemy2
    - shapely
  run:
    - python
    - autocnet
    - redis
    - sqlalchemy
    - geoalchemy2
    - shapely
