package:
  name: autocnet_server
  version: 0.1.0

source:
   git_url: https://github.com/USGS-Astrogeology/autocnet_server.git
   
requirements:
  build:
    - python
    - autocnet-dev
    - redis
  run:
    - python
    - autocnet-dev
    - redis
