### Python Configuration ###
python:
    pyroot: '/usgs/apps/anaconda/envs/autocnet/'
    pybin: '/usgs/apps/anaconda/envs/autocnet/bin/python' # Do not change me


### Cluster Configuration ###
cluster:
    # The number of times to retry a failing cluster job
    maxfailures: 3
    # Which processing queue should be used?
    queue: 'shortall'
    # Location to put <jobid.log> files for cluster jobs
    cluster_log_dir: '/home/acpaquette/logs'
    cluster_submission: 'slurm'  # or `pbs`
    tmp_scratch_dir: '/scratch/acpaquette'

    # The amount of RAM (in MB) to request for jobs
    extractor_memory: 8192
    processing_memory: 4000

### Database Configuration ###
database:
    database_username: 'acpaquette'
    database_password: 'acpaquette'
    database_host: 'smalls'
    database_port: 8001
    pgbouncer_port: 8003
    # The name of the database to connect to.  Tables will be created inside this DB.
    database_name: 'adamdb'
    # The number of seconds to wait while attemping to connect to the DB.
    timeout: 500

# Redis Configuration
redis:
    host: 'smalls'
    port: '8000'
    completed_queue: 'adam:done'
    processing_queue: 'adam:proc'
    working_queue: 'adam:working'

pyro:
    ### Image Adder Configuration ###
    image_adder_uri: 'ia'
    image_adder_port: 8005
    image_adder_host: '0.0.0.0'

    ### Candidate Graph Configuration ###
    candidate_graph_uri: 'ncg'
    candidate_graph_port: 8004
    candidate_graph_host: '0.0.0.0'

### Spatial Reference Setup ###
spatial:
    srid: 949900
    semimajor_rad: 3396190  # in meters
    semiminor_rad: 3376200  # in meters
    proj4_str: '+proj:longlat +a:3396190 +b:3376200 +no_defs'

### Working Directories ###
directories:
    vrt_dir: '/scratch/jlaura/ctx/vrt'

### Developer PATHS ###
developer:
    autocnet_path: '/home/acpaquette/autocnet'
    autocnet_server_path: '/home/acpaquette/repos/autocnet_server'

algorithms:
    ring_match:
        - target_points: 25
          tolerance: 0.01
        - target_points: 20
          tolerance: 0.01
        - target_points: 20
          tolerance: 0.02
        - target_points: 15
          tolerance: 0.025


### Database Creation - DO NOT CHANGE ###
database_creation:
    admin: 'jay'
    password: 'abcde'
